name: weather_data
channels: !!python/tuple
- defaults
dependencies:
- dask=0.11.1
- jupyter=1.0.0
- netcdf4=1.2.4
- notebook=4.2.3
- numpy=1.11.2
- pandas=0.19.0
- python=3.5.2
- requests=2.11.1
- scipy=0.18.1
- xarray=0.8.2

